// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaveStep(arg1:string,arg2:number,arg3:number):Promise<string>;

export function CreateRandomCave(arg1:number,arg2:number,arg3:number):Promise<string>;

export function Generate(arg1:number,arg2:number):Promise<string>;

export function GenerateCave(arg1:string,arg2:number,arg3:number,arg4:number):Promise<string>;

export function LoadCave(arg1:string):Promise<string>;

export function LoadMaze(arg1:string):Promise<string>;

export function SaveMaze(arg1:string,arg2:string):Promise<string>;

export function Solve(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<string>;
