// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaveStep(arg1, arg2, arg3) {
  return window['go']['main']['App']['CaveStep'](arg1, arg2, arg3);
}

export function CreateRandomCave(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateRandomCave'](arg1, arg2, arg3);
}

export function Generate(arg1, arg2) {
  return window['go']['main']['App']['Generate'](arg1, arg2);
}

export function GenerateCave(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateCave'](arg1, arg2, arg3, arg4);
}

export function LoadCave(arg1) {
  return window['go']['main']['App']['LoadCave'](arg1);
}

export function LoadMaze(arg1) {
  return window['go']['main']['App']['LoadMaze'](arg1);
}

export function SaveMaze(arg1, arg2) {
  return window['go']['main']['App']['SaveMaze'](arg1, arg2);
}

export function Solve(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Solve'](arg1, arg2, arg3, arg4, arg5);
}
