// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms",
        "contact": {
            "name": "desmonsu"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/clients": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает массив клиентов с метаинформацией о пагинации",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Получает всех клиентов из базы данных с пагинацией",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "список клиентов с метаинформацией",
                        "schema": {
                            "$ref": "#/definitions/apifromspec_internal_pkg.GetClientsMeta"
                        }
                    },
                    "500": {
                        "description": "failed to fetch clients",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает информацию об успешности операции",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Добавление клиента в базу данных",
                "parameters": [
                    {
                        "description": "Данные для добавления клиента",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apifromspec_internal_pkg.AddClientRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "client created successfully",
                        "schema": {
                            "$ref": "#/definitions/apifromspec_internal_pkg.GetClientsResponse"
                        }
                    },
                    "400": {
                        "description": "wrong input format or validation error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "client already exists",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "failed to add client",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/clients/search": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает массив клиентов, соответствующих запросу. Если клиенты не найдены, возвращает пустой массив.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Получает клиентов из базы данных по имени и фамилии",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Имя клиента",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Фамилия клиента",
                        "name": "surname",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "список клиентов (может быть пустым)",
                        "schema": {
                            "$ref": "#/definitions/apifromspec_internal_pkg.GetClientsResponse"
                        }
                    },
                    "400": {
                        "description": "name and surname are required",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "failed to fetch client",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/clients/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает информацию об успешности операции",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Удаляет клиента из базы данных",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID клиента для удаления",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "client deleted successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "wrong input format or can not parse id from URL",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "client not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "failed to delete client",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/clients/{id}/address": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Заменяет адрес клиента в базе данных",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Смена адреса для клиента",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID клиента",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Параметры нового адреса клиента",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apifromspec_internal_pkg.AddressChangeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "address changed successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "wrong input format or validation error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "id not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "failed to process address",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/image": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Добавление изображения к существующему товару",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "images"
                ],
                "summary": "Добавление изображения продукту",
                "parameters": [
                    {
                        "description": "ID продукта и новое изображение в формате base64",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apifromspec_internal_pkg.AddImageRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "image added and assigned to product successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "wrong input format or validation error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "failed to add image to product",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/image/product/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Получение изображения по id товара",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "images"
                ],
                "summary": "Получение изображения по id товара",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID товара",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "изображение в виде файла",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "invalid product id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "image not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/image/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Получение изображения по id изображения",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "images"
                ],
                "summary": "Получение изображения по id изображения",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID изображения",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "изображение в виде файла",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "invalid image id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "image not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Изменение существующего  изображения в базе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "images"
                ],
                "summary": "Изменение изображения в базе",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID изображения",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "новое изображение в формате base64",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apifromspec_internal_pkg.ChangeImageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "image changed successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "invalid id format, wrong input format or validation error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "image not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "failed to change image",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Удаление  изображения из базы",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "images"
                ],
                "summary": "Удаление изображения",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID изображения",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "image deleted successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "invalid image id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "image not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "failed to delete image",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/products": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает массив товаров. Если товары не найдены, возвращает пустой массив.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Получение всех товаров",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/apifromspec_internal_pkg.GetProductResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "fail to fetch products",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает информацию об успешности операции",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Добавление товара в базу данных",
                "parameters": [
                    {
                        "description": "Данные для добавления товара",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apifromspec_internal_pkg.AddProductRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "product added successfully",
                        "schema": {
                            "$ref": "#/definitions/apifromspec_internal_domain.Product"
                        }
                    },
                    "400": {
                        "description": "wrong input format or validation error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "failed to create product",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/products/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает найденный товар",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Получение товара по id",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID товара",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apifromspec_internal_pkg.GetProductResponse"
                        }
                    },
                    "400": {
                        "description": "wrong input format",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "product not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает информацию об успешности операции",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Удаляет товар из базы данных",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID товара для удаления",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "product deleted successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "wrong input format or can not parse id from URL",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "product not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "failed to delete product",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/products/{id}/subtract": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает информацию об успешности операции",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Вычитание товара из базы при наличии",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID товара",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для вычитания товара",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apifromspec_internal_pkg.SubtractProductRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "amount decreased successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "wrong input format, validation error or insufficient stock",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/suppliers": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает массив поставщиков. Если товары не найдены, возвращает пустой массив.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "suppliers"
                ],
                "summary": "Получение всех поставщиков",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/apifromspec_internal_pkg.GetSupplierResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "fail to fetch suppliers",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Добавление поставщика в базу данных",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "suppliers"
                ],
                "summary": "Добавление поставщика",
                "parameters": [
                    {
                        "description": "Данные для добавления поставщика",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apifromspec_internal_pkg.AddSupplierRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "supplier added successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "wrong input format",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "supplier already exists",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/suppliers/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает найденного поставщика",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "suppliers"
                ],
                "summary": "Получение поставщика по id",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID поставщика",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apifromspec_internal_pkg.GetSupplierResponse"
                        }
                    },
                    "400": {
                        "description": "can not parse id from URL",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "supplier not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "fail to fetch supplier",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает информацию об успешности операции",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "suppliers"
                ],
                "summary": "Удаляет поставщика из базы данных",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID поставщика для удаления",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "supplier deleted successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "wrong input format or can not parse id from URL",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "supplier not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "failed to delete supplier",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/suppliers/{id}/address": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Заменяет адрес поставщика в базе данных",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "suppliers"
                ],
                "summary": "Смена адреса для поставщика",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID поставщика",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Параметры нового адреса поставщика",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apifromspec_internal_pkg.AddressChangeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "address changed successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "wrong input format or validation error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "id not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "failed to process address",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apifromspec_internal_domain.Gender": {
            "type": "string",
            "enum": [
                "M",
                "F"
            ],
            "x-enum-varnames": [
                "Male",
                "Female"
            ]
        },
        "apifromspec_internal_domain.Product": {
            "type": "object",
            "properties": {
                "availableStock": {
                    "type": "integer"
                },
                "category": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "imageID": {
                    "type": "string"
                },
                "lastUpdateDate": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer",
                    "format": "int64"
                },
                "supplierID": {
                    "type": "string"
                }
            }
        },
        "apifromspec_internal_pkg.AddClientRequest": {
            "type": "object",
            "properties": {
                "birthday": {
                    "type": "string",
                    "example": "1990-01-15T00:00:00Z"
                },
                "city": {
                    "type": "string",
                    "example": "Moscow"
                },
                "client_name": {
                    "type": "string",
                    "example": "Ivan"
                },
                "client_surname": {
                    "type": "string",
                    "example": "Petrov"
                },
                "country": {
                    "type": "string",
                    "example": "Russia"
                },
                "gender": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/apifromspec_internal_domain.Gender"
                        }
                    ],
                    "example": "M"
                },
                "street": {
                    "type": "string",
                    "example": "Tverskaya"
                }
            }
        },
        "apifromspec_internal_pkg.AddImageRequest": {
            "type": "object",
            "properties": {
                "image": {
                    "type": "string",
                    "format": "base64"
                },
                "product_id": {
                    "type": "string",
                    "example": "770e8400-e29b-41d4-a716-446655440022"
                }
            }
        },
        "apifromspec_internal_pkg.AddProductRequest": {
            "type": "object",
            "properties": {
                "available_stock": {
                    "type": "integer",
                    "example": 10
                },
                "category": {
                    "type": "string",
                    "example": "Laptops"
                },
                "image": {
                    "type": "string",
                    "format": "base64"
                },
                "name": {
                    "type": "string",
                    "example": "Laptop Air"
                },
                "price": {
                    "type": "integer",
                    "example": 120000
                },
                "supplier_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "apifromspec_internal_pkg.AddSupplierRequest": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string",
                    "example": "Moscow"
                },
                "country": {
                    "type": "string",
                    "example": "Russia"
                },
                "name": {
                    "type": "string",
                    "example": "Tech Wholesale"
                },
                "phone_number": {
                    "type": "string",
                    "example": "+70001112233"
                },
                "street": {
                    "type": "string",
                    "example": "Tverskaya"
                }
            }
        },
        "apifromspec_internal_pkg.AddressChangeRequest": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string",
                    "example": "Saint Petersburg"
                },
                "country": {
                    "type": "string",
                    "example": "Russia"
                },
                "street": {
                    "type": "string",
                    "example": "Nevskiy Prospect"
                }
            }
        },
        "apifromspec_internal_pkg.ChangeImageRequest": {
            "type": "object",
            "properties": {
                "image": {
                    "type": "string",
                    "format": "base64"
                }
            }
        },
        "apifromspec_internal_pkg.GetClientsMeta": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/apifromspec_internal_pkg.GetClientsResponse"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/apifromspec_internal_pkg.Pagination"
                }
            }
        },
        "apifromspec_internal_pkg.GetClientsResponse": {
            "type": "object",
            "properties": {
                "address_id": {
                    "type": "string",
                    "example": "660f8400-e29b-41d4-a716-446655440011"
                },
                "birthday": {
                    "type": "string",
                    "example": "1990-01-15T00:00:00Z"
                },
                "client_name": {
                    "type": "string",
                    "example": "Ivan"
                },
                "client_surname": {
                    "type": "string",
                    "example": "Petrov"
                },
                "gender": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/apifromspec_internal_domain.Gender"
                        }
                    ],
                    "example": "M"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "registration_date": {
                    "type": "string",
                    "example": "2026-04-28T10:00:00Z"
                }
            }
        },
        "apifromspec_internal_pkg.GetProductResponse": {
            "type": "object",
            "properties": {
                "available_stock": {
                    "type": "integer",
                    "example": 10
                },
                "category": {
                    "type": "string",
                    "example": "Laptops"
                },
                "id": {
                    "type": "string",
                    "example": "770e8400-e29b-41d4-a716-446655440022"
                },
                "image_id": {
                    "type": "string",
                    "example": "880e8400-e29b-41d4-a716-446655440033"
                },
                "last_update_date": {
                    "type": "string",
                    "example": "2026-04-28T12:00:00Z"
                },
                "name": {
                    "type": "string",
                    "example": "Laptop Air"
                },
                "price": {
                    "type": "integer",
                    "example": 120000
                },
                "supplier_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "apifromspec_internal_pkg.GetSupplierResponse": {
            "type": "object",
            "properties": {
                "address_id": {
                    "type": "string",
                    "example": "660f8400-e29b-41d4-a716-446655440011"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "name": {
                    "type": "string",
                    "example": "Tech Wholesale"
                },
                "phone_number": {
                    "type": "string",
                    "example": "+70001112233"
                }
            }
        },
        "apifromspec_internal_pkg.Pagination": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer",
                    "example": 3
                },
                "next_offset": {
                    "type": "integer",
                    "example": 1
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                },
                "total": {
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "apifromspec_internal_pkg.SubtractProductRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer",
                    "example": 3
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Введите токен в формате: Bearer {ваш_токен}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "School 21 ApiFromSpec docs",
	Description:      "Реализация RestAPI на Go с использование Swagger для документации",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
