services:
  postgres:
    image: postgres:16-alpine
    container_name: techshop_db
    environment:
      POSTGRES_DB: techshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 10

  migrate:
    image: migrate/migrate:4
    container_name: techshop_migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./app/migrations:/migrations
    entrypoint: [
      "migrate",
      "-path", "/migrations",
      "-database", "postgres://postgres:postgres@postgres:5432/techshop?sslmode=disable",
      "up"
    ]
    restart: "on-failure"

  postgres_auth:
    image: postgres:16-alpine
    container_name: auth_db
    environment:
      POSTGRES_DB: grpc_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 10

  migrate_auth:
    image: migrate/migrate:4
    container_name: auth_migrate
    depends_on:
      postgres_auth:
        condition: service_healthy
    volumes:
      - ./auth/migrations:/migrations
    entrypoint: [
      "migrate",
      "-path", "/migrations",
      "-database", "postgres://postgres:postgres@postgres_auth:5432/grpc_auth?sslmode=disable",
      "up"
    ]
    restart: "on-failure"

  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: techshop-app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      addr: auth:50051
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    restart: on-failure

  auth:
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    container_name: auth_service
    ports:
      - "50051:50051"
    environment:
      DB_HOST: postgres_auth
    depends_on:
      postgres_auth:
        condition: service_healthy
      migrate_auth:
        condition: service_completed_successfully
    restart: on-failure


volumes:
  postgres_data:
  postgres_auth_data: